# .github/workflows/patch-core.yml
name: Patch Mupen64Plus-Next Core

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Patch the core
        run: |
          mkdir -p patched
          python3 scripts/patch_core.py \
            mupen64plus_next_libretro.dll \
            patched/mupen64plus_next_libretro.dll

      - name: Create GitHub Release with patched core
        id: release
        uses: softprops/action-gh-release@v1
        with:
          # The tag for the release—doesn't need to pre-exist if you specify target_commitish
          tag_name: patched-core-${{ github.run_number }}
          name: Patched Mupen64Plus-Next Core v${{ github.run_number }}
          target_commitish: ${{ github.sha }}
          # Attach our single patched DLL
          files: patched/mupen64plus_next_libretro.dll
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
